apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: integration-test-app
spec:
  pipelineSpec:
    params:
    - description: 'Snapshot of the application'
      name: SNAPSHOT
    tasks:
    - name: example-push-task1
      params:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
      taskSpec:     
        steps:
        - image: alpine:3.15
          script: |
            echo "Hello example-push-task!"
            echo $(params.SNAPSHOT)
