apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: integration-nodejs-horreum
spec:
  description: >-
    Run Apache Bench (ab) against devfile-sample (https://github.com/nodeshift-starters/devfile-sample) and upload the
    results to Horreum. 
  params:
    - description: 'Snapshot of the application'
      name: SNAPSHOT
      default: '{"application":"application-sample","components":[{"name":"component-sample","containerImage":"quay.io/redhat-user-workloads-stage/ysubrama-tenant/my-app/devfile-sample-xktr:92aa0ecf7aeb326491d82a196b2db8d78f0f8a9a","source":{"git":{"url":"git@github.com:redhat-appstudio/integration-service.git","revision":"sha256:3703843e80f39188c060a6ed0f524519a682be1e7141fee29b878b1973e9783c"}}}],"artifacts":{}}'
  results:
    - name: TEST_OUTPUT
      value: "$(finally.cleanup.results.TEST_OUTPUT)"
  tasks:
    - name: extract-metadata
      params:
        - name: SNAPSHOT  
          value: $(params.SNAPSHOT)
      taskSpec:
        params:
          - name: SNAPSHOT  
        results:
          - name: url
            description: image url
          - name: test_name
            description: Test name
          - name: exits
            description: Test output 
        steps:
        - image: quay.io/yogananth_subramanian/curl-yq-jq
          script: |
            echo "Extract image details"
            echo $(params.SNAPSHOT)
            echo '$(params.SNAPSHOT)'|jq -r .components[].containerImage |  tr -d '\n\t' | tee $(results.url.path)
            echo '$(params.SNAPSHOT)'|jq -r .components[].name |  tr -d '\n\t' | tee $(results.test_name.path)
            echo -n "yes" | tee $(results.exits.path)
    - name: run-perf
      params:
        - name: url
          value: $(tasks.extract-metadata.results.url)
        - name: test_name
          value: $(tasks.extract-metadata.results.test_name)
      taskSpec:
        steps:      
        - image: quay.io/yogananth_subramanian/curl-yq-jq
          name: step3
          env:
            - name: HORREUM_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: horreum
                  key: horreum_password
            - name: HORREUM_URI
              valueFrom:
                secretKeyRef:
                  name: horreum
                  key: horreum_uri
            - name: HORREUM_USER
              valueFrom:
                secretKeyRef:
                  name: horreum
                  key: horreum_user
            - name: KEYCLOAK_URI 
              valueFrom:
                secretKeyRef:
                  name: horreum
                  key: keycloak_uri
          script: |
            set -xv
            echo "Check for regression!"
            TOKEN=$(curl -s  -k  ${KEYCLOAK_URI}/realms/horreum/protocol/openid-connect/token   -d "username=$HORREUM_USER"  -d "password=$HORREUM_PASSWORD" -d 'grant_type=password' -d 'client_id=horreum-ui' | jq -r .access_token) 
            curl ${HORREUM_URI}/api/test?direction=Ascending -k -s  -X GET  -H 'Authorization: Bearer '${TOKEN}
      runAfter:
        - extract-metadata           

