apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: integration-resolver-pipeline-pass
spec:
  tasks:
    - name: task-success
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/redhat-appstudio/integration-examples 
          - name: revision
            value: main
          - name: pathInRepo
            value: tasks/test_output.yaml
      params:
        - name: RESULT
          value: SUCCESS
    - name: example-perf-task
      runAfter:
      - task-success
      taskSpec:
        steps:
        - image: quay.io/yogananth_subramanian/horreum:latest  
          args:
          - test
          - list
